### PR TITLE
IP matcher

### PR DESCRIPTION
**Pull request by kyessenov**
Signed-off-by: Kuat Yessenov <kuat@google.com>

### CODE REVIEW

**Comment by kyessenov** [comment]
CC @markdroth As you requested this here.

**Review by markdroth — APPROVED** [review]
This looks good to me!

@snowp, can you also review, just to make sure there are no implementation gotchas here that I may not be aware of?  Thanks!

**Comment by markdroth** [comment]
@htuch Any idea what's up with the cancelled CI test here?

**Comment by kyessenov** [comment]
I think @snowp responded on the linked PR. Do you want to merge it?

**Pull request merged**
