### PR TITLE
Synchronize dependencies versions between go.mod and bazel

### PR DESCRIPTION
**Pull request by mmorel-35**
Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>

### CODE REVIEW

**Review by adisuissa — APPROVED** [review]
LGTM, thanks!

**Comment by mmorel-35** [comment]
Hi @adisuissa ,
Do you need someone's approval to merge?
Maybe @phlax ?

**Comment by mmorel-35** [comment]
> im not an api/xds maintainer

I thought so because of the relation with envoy . Sorry for the misunderstanding

**Comment by phlax** [comment]
np - envoy does have api-shepherds which are the same maintainers here i believe

**Comment by mmorel-35** [comment]
Hi @adisuissa ,
Anything to add to merge this as it’s validated ?

**Pull request merged**
