### PR TITLE
Add extension point to StringMatcher

### PR DESCRIPTION
**Pull request by ggreenway**
This mirrors the change made in https://github.com/envoyproxy/envoy/pull/32586

### CODE REVIEW

**Review by adisuissa — DISMISSED** [review]
LGTM, thanks!

**Comment by adisuissa** [comment]
@mmorel-35 Could the changes in #85 cause the CI error?

**Comment by mmorel-35** [comment]
I believe that the CI is saying that the golang hasn't been updated after the modification of the protobuf. Am I misreading it ?

**Comment by adisuissa** [comment]
> I believe that the CI is saying that the golang hasn't been updated after the modification of the protobuf. Am I misreading it ?

I don't remember that we needed to that previously. I wonder what triggered the need for #85. I guess it could be a prior PR, but want to make sure that everything is aligned.

**Comment by ggreenway** [comment]
Ah, I see in DEVOLPER.md the steps I needed to regenerate those files

**Comment by phlax** [comment]
> I don't remember that we needed to that previously

i think this always been the case

**Comment by adisuissa** [comment]
Ack, thanks @mmorel-35 and @phlax! apologies for the unneeded ping.

**Review by adisuissa — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
