### PR TITLE
xDS: Remove extension tag

### PR DESCRIPTION
**Pull request by tyxia**
It seems to cause CI error due to lack of tooling.

Discussion: https://github.com/envoyproxy/envoy/pull/35952#issuecomment-2331791115

### CODE REVIEW

**Comment by tyxia** [comment]
@adisuissa

**Review by adisuissa — COMMENTED** [review]
Can this be in a `#comment` tag?

**Comment by tyxia** [comment]
> Can this be in a `#comment` tag?

I guess it can? But tbh i am very sure if comment will buy us a lot. I am against it though. Updated.

**Comment by adisuissa** [comment]
The idea is to leave it as breadcrumb for if/when eventually we'll have tooling support.

**Review by adisuissa — APPROVED** [review]

**Pull request merged**
